### ISSUE TITLE
一定要国外的服务器吗

### ISSUE THREAD

**Issue by lzcxfz** [kubesre/docker-registry-mirrors#399]
我使用的是腾讯云服务器，在服务器上挂了梯子，curl是可以打开谷歌的，为什么我在服务器运行了镜像加速器后，本地docker也配置好了加速器，拉取，不行呢

**Comment by gebangfeng** [comment]
你是用什么样的方式给服务器配置的代理呢

**Comment by lzcxfz** [comment]
> 你是用什么样的方式给服务器配置的代理呢
clash linux amd64

**Comment by gebangfeng** [comment]
你可以尝试修改下dockerfile,给crgorup用环境变量方式增加代理，代理要写成你服务器内网ip以及clash的端口，不要使用127.0.0.1
```
services:
  gateway:
    image: ghcr.io/wzshiming/nginx-certbot:v1.21.4
    container_name: gateway
    restart: unless-stopped
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
      - ./certbot/conf/:/etc/letsencrypt/
      - ./certbot/www/:/var/www/certbot/
      - ./html:/usr/share/nginx/html
      - ./log/nginx/:/var/log/nginx/
      - ./log/letsencrypt:/var/log/letsencrypt/
    ports:
      - "80:80"
      - "443:443"

  crproxy:
    image: ghcr.io/wzshiming/crproxy/crproxy:v0.1.0
    container_name: crproxy
    restart: unless-stopped
    environment:
      - https_proxy=http://proxy:8080
      - http_proxy=http://proxy:8080
```
